### ISSUE TITLE
IPv6 hostname is incorrectly treated as if it contains a protocol string (v5.0.0)

### ISSUE THREAD

**Issue by Dezzmeister** [jfromaniello/url-join#108]
The following code:
```javascript
urlJoin("[2601:195:c381:3560::f42a]")
```
evaluates to
```javascript
"[2601://195:c381:3560::f42a]"
```

I would expect this to evaluate to `"[2601:195:c381:3560::f42a]"`, because IPv6 addresses surrounded by square brackets are valid hostnames according to https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2. [This line](https://github.com/jfromaniello/url-join/blob/v5.0.0/lib/url-join.js#L19) seems to be the culprit.

If you agree with me that this is a bug, I can open a PR to fix it.

**Comment by jonkoops** [comment]
Hi @Dezzmeister, yes this feels like a bug. If you'd like to open a PR to fix this go right ahead.
