### ISSUE TITLE
Add travis integration

### ISSUE THREAD

**Issue by rauberdaniel** [jfromaniello/url-join#15]
Hey @jfromaniello!
What do you think about adding travis-ci integration? I already added the travis.yml configuration file so it should be quite easy. I also added it for my fork.

**Comment by demurgos** [comment]
Great idea :+1:

**Comment by demurgos** [comment]
Is integrated ? Abandoned ?

**Comment by rauberdaniel** [comment]
@demurgos Is integrated as you can see e.g. in the pull requests section.

**Comment by demurgos** [comment]
Nice!
