### ISSUE TITLE
v1.1.0 doesn't de-dupe "/" in relative URLs

### ISSUE THREAD

**Issue by tivac** [jfromaniello/url-join#16]
It looks like the `/` deduping regex changed after `v0.0.1`

``` js
// v0.0.1
.replace(/[\/]+/g, '/')

// v1.1.0
.replace(/([^:\s])\/+/g, '$1/')
```

which means that relative URLs now don't correctly dedupe leading repeat `/`.

``` js
// v0.0.1
> join("/", "/");
> "/"

// v1.1.0
> join("/", "/");
> "//"
```

I can work around it in my own code but if this is only intended to support absolute URLs that may be worth calling out.

Alternatively an option (added via the system introduced in #14) to specify if the URL is intended to be relative and use the older regex may be worthwhile. Thoughts? I can send a PR if you'd like.

**Comment by nvartolomei** [comment]
Be careful with this, not to break protocol relative urls!

**Comment by jfromaniello** [comment]
seems like a bug

**Comment by tivac** [comment]
@nvartolomei That's why I specifically called out a potential solution being adding a way to switch between relative/absolute URL mode, otherwise this seems like a really rough problem to solve.

**Comment by nvartolomei** [comment]
What if instead when calling join it is checked that slashes are passed as separate arguments then remove them and leave leading double slashes only if are passed in a single argument :) This implementation may be interesting :)

**Comment by eugenet8k** [comment]
Also:
```
> join("", "/some/url");
> "//some/url"
```

**Comment by ArmorDarks** [comment]
That's definitely works wrong... Any plans to fix this? @jfromaniello?

I think that relative protocol should be supported only when it's passed explicitly.

This

``` js
urljoin('/', '/some')
```

should return `/some`

And this

``` js
urljoin('//', '/some')
```

should return `//some`, since we passed in relative protocol explicitly.

Library shouldn't make any assumptions.

**Comment by intijk** [comment]
Is this really fixed, why it is still buggy?

`console.log("urljoin" + urljoin('/', '/some'));`
gives `//some`

Is this project still under maintenance?

**Comment by ArmorDarks** [comment]
We've switched to more reliable [URI.js](https://github.com/medialize/URI.js), but for frontend solutions it would be too big in current state...

**Comment by jfromaniello** [comment]
These cases are already handled in the latest version.
