### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by ArmorDarks** [jfromaniello/url-join#20]
Hi @jfromaniello!

I see some unresolved issues and unmerged PRs, which hangs around for a long time.

Does it mean that library is abandoned and no longer maintained?

Just want to know before pushing any PRs. Don't want to make useless work.

Thanks

**Comment by jfromaniello** [comment]
hi @ArmorDarks sorry about that. 

Yes, I still use this library a lot, but missed the notifications. I will review your PRs.

**Comment by ArmorDarks** [comment]
Hi @jfromaniello 

I'm glad that you're still onto it :) We really didn't want to make another fork and spread community efforts even further.

It would be great if you could also review opened issues, because some of them makes `url-join` very hard to use in certain scenarios. Before any efforts would be taken regarding fixing them (I will try to help), we should discuss and decide does those issues describe indeed desired behavior.
