### ISSUE TITLE
Wrong relative protocol

### ISSUE THREAD

**Issue by ArmorDarks** [jfromaniello/url-join#21]
Case:

``` js
urljoin('/', 'test')
```

becomes `//test`, while expected to be `/test`.

**Comment by keskival** [comment]
https://github.com/jfromaniello/url-join/pull/30

This pull request fixes that case as well. Although it is debatable whether that is a case that should be handled like that in url-join, because it is not an URL at all. But I think just simple paths should also be processed correctly.

**Comment by jfromaniello** [comment]
This has been fixed in v3.
