### ISSUE TITLE
Create query string from options

### ISSUE THREAD

**Issue by DanielMor** [jfromaniello/url-join#28]
It's just an idea of passing an object in the options to generate the query.
```
var query = {
  user: 123,
  b: c
};

urljoin(['http://example.com', 'activity'], { query: query });
```
returns `http://example.com/activity?user=123&b=c`;

**Comment by jfromaniello** [comment]
First of all sorry for the delay!

I think this is beyond the scope of this library, you could use `qs` like this:

```javascript
urljoin('http://example.com', 'activity', '?' + qs.stringify(query));
```

but I will leave this open
