### ISSUE TITLE
Is there a changelog somewhere?

### ISSUE THREAD

**Issue by jim-cooper** [jfromaniello/url-join#32]
Is there a changelog or release notes somewhere? I don't know if it's safe to upgrade from 1.1.0 to 2.0.2. Thanks.

**Comment by ChrisWestcottUK** [comment]
I can see that there is now a version 3.0.0 but also can't find a changelog.  Assuming semantic versioning, I would expect to see breaking changes, but I don't have any idea what these may be.

**Comment by jfromaniello** [comment]
There isn't a changelog yet.

v3 should be compatible with v2 for most common cases and it fixes some issues. But the truth is that v2 was missing a lot of tests so I wanted this to be a conscious decision.

**Comment by ChrisWestcottUK** [comment]
Thank you for the response José.  In my application testing I'm not seeing any breaking changes.

Proper use of semantic versioning does make it much easier for those of us using your library in assessing impact to our code bases.

**Comment by jfromaniello** [comment]
@ChrisWestcottUK understand and I use semantic versioning with all my libraries.. This is what it has been fixed between v2 and v3:

https://github.com/jfromaniello/url-join/pull/35/files

IMHO this should have been a patch actually, but these things where broken for so long that I was afraid other people where relying on broken/undesired behavior.

my apologies

**Comment by ChrisWestcottUK** [comment]
@jfromaniello no need to apologise and thank you for providing the diff here.
