### ISSUE TITLE
2.0.3 breaks existing cases

### ISSUE THREAD

**Issue by contra** [jfromaniello/url-join#34]
Example: `join('http://localhost:3000/v1/municipalities/', ':municipalityId/sources')`

2.0.2: `http://localhost:3000/v1/municipalities/:municipalityId/sources`
2.0.3: `http://localhost:3000/v1/municipalities/://municipalityId/sources`

Cause: https://github.com/jfromaniello/url-join/blob/master/lib/url-join.js#L24
Looks like a bug to me, but if this is intentional behavior it should have been published as a major release.

**Comment by jfromaniello** [comment]
indeed. It looks like a bug introduced after PR #30 cc @keskival can you help us?

**Comment by jfromaniello** [comment]
mmm I can't reproduce it:
```
» cat package.json| json version
2.0.3

» node
> var join = require('./');
undefined
> join('http://localhost:3000/v1/municipalities/', ':municipalityId/sources')
'http://localhost:3000/v1/municipalities/:municipalityId/sources'
```

**Comment by contra** [comment]
Sorry, the input string in the original issue wasn't the right example. This should reproduce:

```js
join('/users/:userId', '/cars/:carId') // output: /users/://userId/cars/:carId
```

**Comment by jfromaniello** [comment]
ok, I reverted to the previos behavior and leaved the tests cases of #30  with `.skip`. I also added a test for this case.
