### ISSUE TITLE
Duplicate slashes "//" in urls when a part is empty

### ISSUE THREAD

**Issue by crccheck** [jfromaniello/url-join#36]
url-join version 3.0.0

```
> urlJoin('path/', '', '/test')
'path/test'  # expected
'path//test' # actual

> urlJoin('path', '', /test')
'path/test'  # expected
'path//test' # actual

> urlJoin('path', null, /test')
'path/test'  # expected
'path//test' # actual

```

In more detail, I've got an array of bits of a url. Sometimes, parts are optional, so I set them to '' and assume the url joiner will throw away the empty bits

**Comment by crccheck** [comment]
ugh, submitted before I wrote the issue

**Comment by crccheck** [comment]
as prior art, this is the same behavior as Node's built in `path.join`:
```
$ node
> const path = require('path')
undefined
> path.join('hi')
'hi'
> path.join('hi', 'there')
'hi/there'
> path.join('hi', '', 'there')
'hi/there'
```

**Comment by jfromaniello** [comment]
Thanks for reporting this. I just published v4 addressing this the same way that `path.join` does.

**Comment by shellscape** [comment]
@jfromaniello this could have been documented much better than it is in the changelog. This also effects `urlJoin('', 'foo.js');`. Previously the return value was `/foo.js`, in version 4, it's `foo.js`. Folks that aren't aware of the nuances of `path.join` will be thrown off by this because of prior expected behavior of the module.

**Comment by crccheck** [comment]
ooh, I didn't even think of that use case. I'll try to keep that in mind in the future too. For reference, here's Node's `path.join` with some variations of that case:

```
> path.join('', 'foo.js')
'foo.js'
> path.join('', '/foo.js')
'/foo.js'
> path.join('/', 'foo.js')
'/foo.js'
> path.join('/', '/foo.js')
'/foo.js'
```

**Comment by jfromaniello** [comment]
I think I've reached a point in this library where every time I merge a PR I break someone else use case. I am trying to figure a way, I think to begin with we need a lot more of tests and specifications.
