### ISSUE TITLE
it is a bug?

### ISSUE THREAD

**Issue by tianyingchun** [jfromaniello/url-join#40]
urlJoin([ 'http://me.ly.com:3002', '/', '/demo/scrollbar' )
==>'http://me.ly.com:3002//demo/scrollbar'

it should be http://me.ly.com:3002/demo/scrollbar

maybe it should removed unnecessary slash....

**Comment by jfromaniello** [comment]
yes, indeed, it seems a bug

**Comment by stasberkov** [comment]
Please fix it. I also suffer from this defect .

**Comment by jonkoops** [comment]
This bug has been fixed at some point as it is no longer reproducible on the latest `main`.
