### ISSUE TITLE
Query params and anchor tags not removed from base urls

### ISSUE THREAD

**Issue by carmandrew** [jfromaniello/url-join#43]
When a base URL contains query params or anchors, they should be removed:
```
urljoin('http://www.google.com?foo=bar', '/a')
// got: http://www.google.com?foo=bar/a
// desired: http://www.google.com/a

urljoin('http://www.google.com#foo', '/a')
// got: http://www.google.com#foo/a
// desired: http://www.google.com/a
```

For context, both [Python's `urljoin`](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin) and [Golang's `url.ResolveReference`](https://golang.org/pkg/net/url/#URL.ResolveReference) handle it in the "desired" way.

**Comment by LvChengbin** [comment]
I think this feature should not appear in a URL joining method, it might should be in a `URL.resolve`.

**Comment by jonkoops** [comment]
I think this is out of scope for this library, you should provide the segments of a URL in a valid order. Also, having a path inside of the hash of a URL is very common for client side routing, and there is no easy way to detect the intention.
