### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by itpmngt** [jfromaniello/url-join#49]
There are scenarios that normalize() function is called with an empty `strArray` - could we implement some safety (old code bases that uses url-join are becoming incompatible)

I will we submit a PR for your consideration

Thanks

**Comment by itpmngt** [comment]
Don't have permissions to submit PR - the suggestion is for:

  function normalize (strArray) {
    if(!strArray || !strArray[0]) return ""
    var resultArray = [];

.
.
.
on top of the file

**Comment by jfromaniello** [comment]
Thank you for reporting this. I fixed in `v4.0.1`.
