### ISSUE TITLE
Auto-Normalize paths returned by url-join

### ISSUE THREAD

**Issue by pviolette3** [jfromaniello/url-join#5]
`urljoin('http://foo.com/subdir/a.html', '../b.html')` currently returns `http://foo.com/subdir/a.html/../b.html` but should return `http://foo.com/subdir/b.html`

**Comment by pviolette3** [comment]
After looking at the code, I realized this library is a very light weight implementation of path joining that is < 10 LOC doing some hard coded regex replacements and then joining the arguments with '/'. Very fast and light for browser, but somewhat incomplete for server side use cases.

[path#join](https://nodejs.org/api/path.html#path_path_join_path1_path2) handles this specific case for the issue. Would you say this function is a subset of the use cases for path#join?

**Comment by pviolette3** [comment]
Err, sorry. [url#resolve](https://nodejs.org/docs/latest/api/url.html#url_url_resolve_from_to) is the correct function.

**Comment by jfromaniello** [comment]
Yes, `url.resolve` was added sometime after I wrote this.

I use this library mostly for cases where I want to do something like `foo = join(some_url_in_var, '/foo');` and I don't know/or not sure/or I don't want to dig the value of that variable.

**Comment by pviolette3** [comment]
Ok. Makes sense :)
