### ISSUE TITLE
No support for hashbang (#!) urls?

### ISSUE THREAD

**Issue by papaiatis** [jfromaniello/url-join#6]
For example, I have this working url: "www.example.com/#!/home".
I can't seem to configure this component to generate such URLs. I always get "www.example.com#!/home".

Note that hashbang URLs are widely used among SPA websites (AngularJs, Durandal, etc).

**Comment by jfromaniello** [comment]
can you show me an example of how you would expect it to work? thanks!

**Comment by papaiatis** [comment]
For example I would write the following code: 

`urljoin('http://www.example.com/#!/', 'a', '/b/cd', '?foo=123');`

Which would generate: `http://www.example.com/#!/a/b/cd?foo=123`

**Comment by srph** [comment]
Having the same issue.

**Comment by sebaplaza** [comment]
Same issue here, i'm using to call angularjs routes (they always have the # character).

**Comment by rauberdaniel** [comment]
Hey everyone, this should be fixed now :)

**Comment by matthussey** [comment]
Hi,
I'm getting a very similar issue when using angular ui router urls.
I get the following happening:
urljoin('www.google.com', '#') --> www.google.com/#/ --> Correct
urljoin('www.google.com', '#/something') -> www.google.com#/something/ --> WRONG Missing the first slash
urljoin('www.google.com', '#', 'something') --> www.google.com#/something/ --> WRONG Missing the first slash
urljoin('www.google.com/#/', 'something') --> www.google.com#/something/ --> WRONG Missing the first slash
I am using 1.1.0.

**Comment by ArmorDarks** [comment]
Seems like a bug to me. See my comment in this PR for more details: https://github.com/jfromaniello/url-join/pull/19#issuecomment-282554964

**Comment by jfromaniello** [comment]
I am closing this issue because the first problem described by @papaiatis has already been fixed.
