### ISSUE TITLE
Allow passing an array instead single arguments

### ISSUE THREAD

**Issue by strarsis** [jfromaniello/url-join#7]
It would result in more intuitive code on the usage side 
if an array could be passed instead single arguments.

Currently I have to use this for passing an array to it:
````
var new = urljoin.apply(this, segments);
````

Thank you and
with best regards

**Comment by sholladay** [comment]
FWIW, ES2015 makes this easier. As of Node 5.0.0 you can simply do:
````javascript
let url = urlJoin(...arguments);
````

**Comment by nemild** [comment]
@jfromaniello It's also a simple pull request to test if an array is passed, and treat that differently. Happy to contribute it if you'd like.

**Comment by jfromaniello** [comment]
This is now supported in version `v1.1.0`
