### ISSUE TITLE
 SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by harsha09** [jfromaniello/url-join#90]
When working with Jest I've encountered the below error message.

 SyntaxError: Unexpected token 'export'

    > 1 | import urlJoin from 'url-join';

adding `"node_modules/(?!(url-join)/)"` in `transformIgnorePatterns` did not help.

**Comment by jonkoops** [comment]
You'll have to run Jest in ESM mode or include the dependency explicitly to transform it into CommonJS. More information can be found in the [Jest documentation](https://jestjs.io/docs/ecmascript-modules).
