### ISSUE TITLE
doesn't join url like Python urljoin

### ISSUE THREAD

**Issue by ximaff** [jfromaniello/url-join#92]
Hello,

doesn't work  like pyhon urljoin function : 

PY:
![image](https://user-images.githubusercontent.com/14837644/204110277-43675eda-e8d1-41a1-bcc4-c32e9b0a84d6.png)

JS:
![image](https://user-images.githubusercontent.com/14837644/204110261-b2583063-33dd-481b-8e23-f367be40be76.png)

python urljoin function  join correctly the url : https://www.edgedb.com/favicon-32x32.png

**Comment by jonkoops** [comment]
I don't believe this is a bug, this library never claims to be the same as the implementation in Python.
